# Generated by Django 5.1.3 on 2025-03-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='civic1.login'),
            preserve_default=False,
        ),
    ]
