# Generated by Django 5.1.3 on 2025-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0002_user_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='idcardno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
