# Generated by Django 5.1.3 on 2025-03-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0003_user_contactno_user_idcardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
