# Generated by Django 5.1.3 on 2025-03-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0005_alter_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
