# Generated by Django 5.1.3 on 2025-03-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0006_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=models.TextField(),
        ),
    ]
