# Generated by Django 5.1.3 on 2025-03-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0007_alter_notifications_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('suggestion', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
            ],
        ),
    ]
