# Generated by Django 5.1.3 on 2025-03-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0008_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electiontype', models.CharField(max_length=50)),
                ('electiondate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('details', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
