# Generated by Django 5.1.3 on 2025-03-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0009_election'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationcategory', models.CharField(max_length=100)),
                ('Information', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
