# Generated by Django 5.1.3 on 2025-03-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0010_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Information',
            new_name='information',
        ),
    ]
