# Generated by Django 5.1.3 on 2025-03-28 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0011_rename_information_information_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politicalparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partylogo', models.ImageField(upload_to='photos')),
                ('partyname', models.CharField(max_length=50)),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
            ],
        ),
    ]
