# Generated by Django 5.1.3 on 2025-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0013_alter_politicalparties_partylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparties',
            name='partylogo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
