# Generated by Django 5.1.3 on 2025-04-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0014_alter_politicalparties_partylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.politicalparties')),
            ],
        ),
    ]
