# Generated by Django 5.1.3 on 2025-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0015_electionmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmember',
            name='municipality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electionmember',
            name='panchayat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electionmember',
            name='taluk',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
