# Generated by Django 5.1.3 on 2025-04-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0016_electionmember_municipality_electionmember_panchayat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
                ('memberid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.electionmember')),
            ],
        ),
    ]
