# Generated by Django 5.1.3 on 2025-04-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0017_votenow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenow',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
