# Generated by Django 5.1.3 on 2025-04-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0018_alter_votenow_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenow',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user'),
        ),
    ]
