# Generated by Django 5.1.3 on 2025-04-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0019_alter_votenow_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='publishstatus',
            field=models.IntegerField(default=0),
        ),
    ]
