# Generated by Django 5.1.3 on 2025-04-10 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0021_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('venue', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate')),
            ],
        ),
    ]
