# Generated by Django 5.1.3 on 2025-04-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0022_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='time',
            field=models.TimeField(),
        ),
    ]
