# Generated by Django 5.1.3 on 2025-04-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0023_alter_campaign_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nominationpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=100)),
                ('nameonballotpaper', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=20)),
            ],
        ),
    ]
