# Generated by Django 5.1.3 on 2025-04-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0024_nominationpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpaper',
            name='cancelstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nominationpaper',
            name='loginid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate'),
            preserve_default=False,
        ),
    ]
