# Generated by Django 5.1.3 on 2025-04-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0025_nominationpaper_cancelstatus_nominationpaper_loginid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominationpaper',
            name='cancelstatus',
        ),
    ]
