# Generated by Django 5.1.3 on 2025-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0026_remove_nominationpaper_cancelstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpaper',
            name='cancelstatus',
            field=models.IntegerField(default=0),
        ),
    ]
