# Generated by Django 5.1.3 on 2025-04-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0027_nominationpaper_cancelstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='civic1.login'),
        ),
    ]
