# Generated by Django 5.1.3 on 2025-04-22 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0030_alter_candidate_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpaper',
            name='electionid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='civic1.election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login'),
        ),
    ]
