# Generated by Django 5.1.3 on 2025-04-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0031_nominationpaper_electionid_alter_candidate_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpaper',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
