# Generated by Django 5.1.3 on 2025-04-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0035_alter_candidate_party'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparties',
            name='electionid',
        ),
    ]
