# Generated by Django 5.1.3 on 2025-04-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0036_remove_politicalparties_electionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votenow',
            name='memberid',
        ),
        migrations.AddField(
            model_name='votenow',
            name='candidateid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate'),
            preserve_default=False,
        ),
    ]
