# Generated by Django 5.1.3 on 2025-05-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0037_remove_votenow_memberid_votenow_candidateid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
