# Generated by Django 5.1.3 on 2025-05-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0038_candidateforum'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinOnlineForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('candidateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate')),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidateforum')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user')),
            ],
        ),
    ]
