# Generated by Django 5.1.3 on 2025-05-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0039_joinonlineforum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinonlineforum',
            name='candidateid',
        ),
        migrations.AlterField(
            model_name='joinonlineforum',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login'),
        ),
    ]
