# Generated by Django 5.1.3 on 2025-05-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0040_remove_joinonlineforum_candidateid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidateforum')),
                ('receiverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='civic1.login')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='civic1.login')),
            ],
        ),
    ]
