# Generated by Django 5.1.3 on 2025-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0041_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiverid',
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
