# Generated by Django 5.1.3 on 2025-05-26 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0042_remove_chat_receiverid_alter_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenow',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login'),
        ),
    ]
