# Generated by Django 5.1.3 on 2025-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0043_alter_votenow_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='venue',
            field=models.TextField(),
        ),
    ]
