# Generated by Django 5.1.3 on 2025-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0045_alter_campaign_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='details',
            field=models.TextField(),
        ),
    ]
