# Generated by Django 5.1.3 on 2025-06-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0046_alter_campaign_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='adharcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='idcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='idcardno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='rationcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rationcardno',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='adharcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='idcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='rationcard',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
