# Generated by Django 5.1.3 on 2025-06-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0047_candidate_adharcard_candidate_idcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
