# Generated by Django 5.1.3 on 2025-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0049_alter_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adhar',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
