# Generated by Django 5.1.3 on 2025-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0050_alter_user_adhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
