# Generated by Django 5.1.3 on 2025-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0051_candidate_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='adhar',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
