# Generated by Django 5.1.3 on 2025-06-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0052_alter_candidate_adhar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='party',
        ),
        migrations.AddField(
            model_name='nominationpaper',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civic1.politicalparties'),
        ),
    ]
