# Generated by Django 5.1.3 on 2025-06-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0053_remove_candidate_party_nominationpaper_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='ward',
        ),
    ]
