# Generated by Django 5.1.3 on 2025-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0054_rename_city_user_ward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='rationcard',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rationcard',
        ),
        migrations.AddField(
            model_name='candidate',
            name='ward',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
