# Generated by Django 5.1.3 on 2025-06-13 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('civic1', '0056_remove_campaign_loginid_remove_candidate_loginid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('adhar', models.CharField(max_length=50, unique=True)),
                ('idcardno', models.CharField(max_length=100)),
                ('rationcardno', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=100)),
                ('panchayat', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=10)),
                ('adharcard', models.ImageField(null=True, upload_to='photo')),
                ('idcard', models.ImageField(null=True, upload_to='photo')),
                ('otp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electiontype', models.CharField(max_length=50)),
                ('electiondate', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('details', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('publishstatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informationcategory', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politicalparties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partylogo', models.ImageField(upload_to='photos')),
                ('partyname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JoinOnlineForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidateforum')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('forumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidateforum')),
                ('senderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='civic1.login')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login'),
        ),
        migrations.CreateModel(
            name='Nominationpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=100)),
                ('nameonballotpaper', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=20)),
                ('cancelstatus', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civic1.politicalparties')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('panchayat', models.CharField(max_length=50, null=True)),
                ('municipality', models.CharField(max_length=50, null=True)),
                ('taluk', models.CharField(max_length=50)),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
                ('partyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.politicalparties')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('suggestion', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=100)),
                ('panchayat', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('adhar', models.CharField(max_length=50, unique=True)),
                ('idcardno', models.CharField(max_length=100)),
                ('otp', models.IntegerField(null=True)),
                ('rationcardno', models.CharField(max_length=50)),
                ('adharcard', models.ImageField(null=True, upload_to='photo')),
                ('idcard', models.ImageField(null=True, upload_to='photo')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
            ],
        ),
        migrations.CreateModel(
            name='VoteNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('candidateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.candidate')),
                ('electionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.election')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.login')),
            ],
        ),
    ]
