# Generated by Django 5.1.3 on 2025-06-13 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0057_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominationpaper',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user'),
        ),
    ]
