# Generated by Django 5.1.3 on 2025-06-13 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0058_alter_nominationpaper_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenow',
            name='candidateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user'),
        ),
    ]
