# Generated by Django 5.1.3 on 2025-06-14 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0059_alter_votenow_candidateid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user'),
        ),
    ]
