# Generated by Django 5.1.3 on 2025-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0060_alter_campaign_loginid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparties',
            name='partylogo',
            field=models.ImageField(default=0, upload_to='photos'),
        ),
    ]
