# Generated by Django 5.1.3 on 2025-06-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0061_alter_politicalparties_partylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparties',
            name='partylogo',
            field=models.ImageField(default=0, null=True, upload_to='photos'),
        ),
    ]
