# Generated by Django 5.1.3 on 2025-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0063_alter_politicalparties_partylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparties',
            name='partylogo',
            field=models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos'),
        ),
    ]
