# Generated by Django 5.1.3 on 2025-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0064_alter_politicalparties_partylogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
