# Generated by Django 5.1.3 on 2025-06-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0065_alter_login_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationpaper',
            name='independentpartylogo',
            field=models.ImageField(blank=True, null=True, upload_to='photo'),
        ),
    ]
