# Generated by Django 5.1.3 on 2025-06-16 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0066_nominationpaper_independentpartylogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('complaint', models.TextField()),
                ('currentdate', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civic1.user')),
            ],
        ),
    ]
