# Generated by Django 5.2.3 on 2025-06-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civic1', '0067_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votenow',
            name='candidateid',
            field=models.TextField(),
        ),
    ]
